{
  "Impact": "The complete impact of this vulnerability is not yet known.", 
  "CVSS_SecurityRequirementsIR": "", 
  "CVSS_EnvironmentalVector": "", 
  "Title": "Python \"repr\" function fails to handle crafted wide character UTF-32/UCS-4 strings", 
  "DateFirstPublished": "", 
  "CVSS_AccessVector": "", 
  "CAM_ScoreCurrentWidelyKnown": 0, 
  "IDNumber": "169512", 
  "SystemsAffectedPreamble": "", 
  "CVSS_SecurityRequirementsCR": "", 
  "CVSS_Authenication": "", 
  "CVSS_BaseScore": "", 
  "CAM_EaseOfExploitation": "0", 
  "IPProtocol": "", 
  "CERTAdvisory": "", 
  "CVSS_CollateralDamagePotential": "", 
  "Revision": 8, 
  "CVEIDs": "CVE-2006-4980", 
  "VRDA_D1_DirectReport": "0", 
  "CAM_WidelyKnown": "0", 
  "CAM_Population": "0", 
  "Description": "", 
  "CVSS_AccessComplexity": "", 
  "CVSS_SecurityRequirementsAR": "", 
  "Resolution": "The CERT/CC is currently unaware of a practical solution to this problem.", 
  "Author": "This document was written by Jeff Gennari.", 
  "CAM_Exploitation": "0", 
  "DateLastUpdated": "2007-01-11T08:44:00-05:00", 
  "CVSS_IntegrityImpact": "", 
  "VRDA_D1_Population": "3", 
  "CVSS_TemporalVector": "", 
  "CVSS_ReportConfidence": "", 
  "CVSS_ConfidentialityImpact": "", 
  "CVSS_BaseVector": "", 
  "VulnerabilityCount": 1, 
  "CVSS_Exploitability": "", 
  "ThanksAndCredit": "", 
  "US-CERTTechnicalAlert": "", 
  "CAM_ScoreCurrentWidelyKnownExploited": 0, 
  "CVSS_TemporalScore": "", 
  "VRDA_D1_Impact": "3", 
  "CVSS_TargetDistribution": "", 
  "CAM_InternetInfrastructure": "0", 
  "CVSS_RemediationLevel": "", 
  "Workarounds": "", 
  "ID": "VU#169512", 
  "CVSS_AvailabilityImpact": "", 
  "CAM_ScoreCurrent": 0, 
  "Overview": "", 
  "CAM_Impact": "0", 
  "DatePublic": "2006-10-06T00:00:00", 
  "DateCreated": "2006-10-26T12:40:19-04:00", 
  "References": [
    "http://sourceforge.net/tracker/index.php?func=detail&aid=1541585&group_id=5470&atid=305470 ", 
    "http://zoehep.xent.com/~bsittler/python2.4-2.4.3_unicodeobject.c.diff ", 
    "https://launchpad.net/distros/ubuntu/+source/python2.4/+bug/56633 ", 
    "http://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=208162 ", 
    "https://issues.rpath.com/browse/RPL-702 ", 
    "http://support.avaya.com/elmodocs2/security/ASA-2006-229.htm ", 
    "http://www.securityfocus.com/bid/20376 ", 
    "http://www.frsirt.com/english/advisories/2006/3940 ", 
    "http://securitytracker.com/id?1017019 ", 
    "http://secunia.com/advisories/22276 ", 
    "http://secunia.com/advisories/22303 ", 
    "http://secunia.com/advisories/22357 ", 
    "http://secunia.com/advisories/22297 ", 
    "http://secunia.com/advisories/22358 ", 
    "http://secunia.com/advisories/22379 ", 
    "http://secunia.com/advisories/22448 ", 
    "http://secunia.com/advisories/22512 ", 
    "http://secunia.com/advisories/22639/", 
    "http://xforce.iss.net/xforce/xfdb/29408 ", 
    "http://secunia.com/advisories/23680/"
  ], 
  "Keywords": [
    "Python", 
    "DoS", 
    "arbitrary code execution", 
    "repr", 
    "UTF-32", 
    "UCS-4"
  ], 
  "CVSS_EnvironmentalScore": "", 
  "CAM_AttackerAccessRequired": "0"
}